# ワークフローの名前
name: Workflow Trigger Check

# ワークフローが実行されるトリガーを指定
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    tags-ignore:
      - '**rc**' # タグ名にrcが含まれるものを除外

# 実行されるジョブを定義
jobs:
  # "check" という名前のジョブ
  check:
    # ジョブを実行する仮想環境の種類
    runs-on: ubuntu-latest

    # ジョブのステップ
    steps:
      # 1. チェックアウトのステップ (必須ではありませんが、通常は含めます)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 起動確認のメッセージを出力するステップ
      - name: Show trigger confirmation message
        run: echo "🎉 Workflow triggered successfully!"
